"""author not unique

Revision ID: 450611313e0f
Revises: 659fa46398f9
Create Date: 2025-05-03 15:51:04.224612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450611313e0f'
down_revision = '659fa46398f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_author')
        batch_op.create_index(batch_op.f('ix_post_author'), ['author'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_author'))
        batch_op.create_index('ix_post_author', ['author'], unique=1)

    # ### end Alembic commands ###
